### PR TITLE
Missing `chalk` dependency

### PR DESCRIPTION
**Pull request by carvinlo**
Missing `chalk@^2.2.0` dependency

### CODE REVIEW

**Comment by FlorianRappl** [comment]
How can this be missing?

`piral-cli` already comes with it. So its a transitive one.

(If you want to have this building / published you'll need to change the version in the `package.json`.)

**Comment by carvinlo** [comment]
Oh, caused by my problem.
If the version number of the `chalk` is not declared, it will makes `piral-cli-webpack` reference `chalk@3.0.0` that `jest` depends on in the monorepo.

**Comment by FlorianRappl** [comment]
I see - we'll include the same ref then as `piral-cli` to avoid this issue!

**Comment by FlorianRappl** [comment]
Thanks for the explanation!

:beers:

**Pull request merged**
